name: testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Generate venv and activate
      run: |
        python -m venv .venv
        chmod +x .venv/bin/activate
        source .venv/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install
    - name: Test with pytest
      run: |
        python -m pytest --cov --cov-report xml
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.xml
